### ISSUE TITLE
Spawn messages

### ISSUE THREAD

**Issue by EmporiumPvP** [diamond-gold/MiniBosses#42]
Being able to add a spawn/respawn message to each boss would be nice.

Tags like {BOSS} {LOCATION} to be able to add more depth to the message would be an nice touch too

maybe possibility for random respawn message?

respawn-messages: (1 line for 1 pre set spawn message, multiple for random spawn message)
  - {BOSS} has spawned at {LOCATION}
  - {BOSS} has been spotted by {LOCATION}
  - A mystery Boss has been spotted by {LOCATION}
  
etc

**Comment by diamond-gold** [comment]
Good idea, just wondering if it is better to execute commands instead instead of broadcasting message to everyone. That way it may be more flexible, for example if you have some broadcast plugin that could customize who you want to send it to, and how you want to send it (title / tip etc). You can also do more than just sending a message, there are many possiblities.

**Comment by EmporiumPvP** [comment]
maybe you could do it similar to how you added commands in the config

You could do 

spawn-message:
 - COMMAND "broadcast this is the spawn message"
 - MESSAGE "this is the broadcast message"
